config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'admin', controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
  }

  root 'pages#home'

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create]
  end

  namespace :admin do
    get '/' => 'posts#index'
    resources :posts, except: [:show]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy, inverse_of: :category

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :author, :content, :post, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category, inverse_of: :posts
  has_many :comments

  validates :title, :text, :category, presence: true

  scope :recent, -> { order(created_at: :desc) }

  before_create :generate_slug

  dragonfly_accessor :image

  def excerpt
    text.truncate(50)
  end

  private

  def generate_slug
    self.slug = title.parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :authenticate_user!

    layout 'admin'
  end
end

app/controllers/admin/passwords_controller.rb
module Admin
  class PasswordsController < ::Devise::PasswordsController
    layout 'admin'
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::BaseController
    def index
      @posts = Post.all
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to admin_posts_path, alert: 'Post criado com sucesso'
      else
        flash[:alert] = 'Verifique os dados inseridos'
        render :new
      end
    end

    def edit
      @post = Post.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_posts_path, alert: 'Post não encontrado'
    end

    def update
      @post = Post.find(params[:id])

      if @post.update(post_params)
        redirect_to admin_posts_path, alert: 'Post atualizado com sucesso'
      else
        flash[:alert] = 'Verifique os dados inseridos'
        render :edit
      end
    end

    def destroy
      @post = Post.find_by_id(params[:id])
      @post.destroy if @post.present?

      redirect_to admin_posts_path, alert: 'Post deletado com sucesso'
    end

    private

    def post_params
      params.require(:post).permit(:category_id, :title, :text, :image)
    end
  end
end

app/controllers/admin/sessions_controller.rb
module Admin
  class SessionsController < ::Devise::SessionsController
    layout 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    post.comments.create!(comment_params)

    redirect_to post_path(post)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @name = 'Patrick'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.recent.limit(5)

    respond_to do |format|
      format.html
      format.json { render json: @posts.as_json }
    end
  end

  def show
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/_form.html.erb
<%= simple_form_for [:admin, @post] do |f| %>
  <%= f.input :category_id, collection: Category.all, prompt: 'Escolha uma opção' %>
  <%= f.input :title %>
  <%= f.input :text %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/admin/posts/_post.html.erb
<tr>
  <td><%= post.id %></td>
  <td><%= link_to(post.title, post_path(post)) %></td>
  <td><%= I18n.l(post.created_at, format: '%d/%m %H:%M') %></td>
  <td>
    <%= link_to('Editar', edit_admin_post_path(post), class: 'tiny button') %>
    <%= link_to('Deletar', admin_post_path(post), class: 'tiny button', method: :delete ) %>
  </td>
</tr>

app/views/admin/posts/edit.html.erb
<h2>Editar Post</h2>
<%= render 'form' %>

app/views/admin/posts/index.html.erb
<h1>Posts</h1>
<%= link_to('Novo post', new_admin_post_path, class: 'button') %>

<table>
  <thead>
    <tr>
      <td>ID</td>
      <td>Título</td>
      <td>Cadastro</td>
      <td>Ações</td>
    </tr>
  </thead>

  <tbody>
    <%= render @posts %>
  </tbody>
</table>

app/views/admin/posts/new.html.erb
<h2>Novo Post</h2>
<%= render 'form' %>

app/views/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert-box radius <%= type %>"><%= message %></div>
<% end %>

app/views/comments/_comment.html.erb
<p><strong><%= comment.author %></strong> <%= comment.content %></p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container">
      <%= render 'application/flash_messages' %>

      <% if user_signed_in? %>
      <p>Olá <strong><%= current_user.email %></strong> - <%= link_to('Sair', destroy_user_session_path, method: :delete) %></p>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1><%= @name %></h1>

<%= link_to('Veja nossos posts', posts_path) %>

app/views/posts/_post.html.erb
<h1><%= link_to(post.title, post_path(post)) %></h1>
<%= simple_format(post.excerpt) %>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= image_tag(@post.image.thumb('200x200').url) %>
<%= simple_format(@post.text) %>

<div class="comments">
  <h2>Nossos <%= @post.comments.count %> comentários</h2>

  <%= render @post.comments %>

  <%= form_for [@post, @post.comments.new] do |f| %>
    <div>
      <%= f.label :author %>
      <%= f.text_field :author %>
    </div>

    <div>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>

    <div class="form-actions">
      <%= f.submit "Enviar" %>
    </div>

  <% end %>
</div>